image: ds_logging_behaviour
version: latest

input_path: ./input/
input_file: repositories_data.csv

output_path: ./output/

assembler:
  default: extractor

semgrep_path: ./input/semgrep/
semgrep_count_rules: count_rules.yaml
semgrep_level_rules: levels_rules.yaml