image: ds_logging_behaviour
version: latest

input_path: ./input/
input_file: ./input/1000data.csv
output_path: ./output/
#output_file: ./output/LogMetrics-Summarized.csv

assembler:
  default: extractor

semgrep_logcount: ./input/semgrep.yaml
semgrep_loglevel: ./input/level_semgrep.yaml