image: ds_logging_behaviour
version: latest

assembler:
  default: downloader

# Folders
path_input: ./input/
path_output: ./output/
path_repositories: ../repositories/
path_semgrep: ./input/semgrep/

# Input Files
input_repo_list: repositories_data_test.csv
input_semgrep_repo_metrics: repo_metrics.yaml
input_semgrep_log_levels: log_levels.yaml

# Output Files
output_manifest: repo-manifest.csv
output_metrics: repo-metrics.csv
output_logs: repo-logs.csv
output_logs_sample: repo-logs-sample.csv
output_gini_indexes: repo-gini-indexes.csv

# Params
log_sample_size: 100
